version: '3.6'
services:
  postgres:
    container_name: jest_hangs
    build:
      context: .
      dockerfile: pg-Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 6432:5432

volumes:
  db_data: