version: '3.6'
services:
  pgDB:
    container_name: enum_not_generated
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 6432:5432

volumes:
  db_data: